name = "alphascent"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat", "nodejs_als"]
pages_build_output_dir = ".vercel/output/static"

# Pages configuration
[env.production]
vars = { ENVIRONMENT = "production" }

# D1 Database binding
[[env.production.d1_databases]]
binding = "DB"
database_name = "alphascent-db"
database_id = "62dd9973-d9f1-4229-945e-e77d4b53f075"

# R2 Storage binding
[[env.production.r2_buckets]]
binding = "R2"
bucket_name = "alphascent-figures"

[env.preview]
vars = { ENVIRONMENT = "preview" }

